const BLOCK_COMMENTS: Record<string, string> = {
  providers: "Providers (reviewers + judges). Models & OAuth-vs-OpenRouter are your choice.",
  phases: "Review pipeline: reviewers, critic, brain (repo memory), fpLedger, contextDocs.",
  docReview: "Optional plan/spec review.",
  weeklyReport: "Weekly report auto-snapshot on rollover.",
};

function renderKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}

// Renders a JS object/array/scalar literal. `indent` is the depth of the line that
// holds the opening brace/bracket; contents sit one level deeper.
function renderValue(v: unknown, indent: number): string {
  const pad = "  ".repeat(indent);
  const padIn = "  ".repeat(indent + 1);
  if (v === null) return "null";
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    const items = v.map((x) => padIn + renderValue(x, indent + 1));
    return `[\n${items.join(",\n")}\n${pad}]`;
  }
  if (typeof v === "object") {
    const keys = Object.keys(v as Record<string, unknown>);
    if (keys.length === 0) return "{}";
    const items = keys.map(
      (k) =>
        `${padIn}${renderKey(k)}: ${renderValue((v as Record<string, unknown>)[k], indent + 1)}`,
    );
    return `{\n${items.join(",\n")}\n${pad}}`;
  }
  if (typeof v === "string") return JSON.stringify(v);
  return String(v); // number | boolean
}

// Renders a config partial as a data-only `export default {}` document. A one-line
// comment precedes each known top-level block; the literal parser ignores comments.
export function serializeConfig(partial: Record<string, unknown>): string {
  const keys = Object.keys(partial);
  const body = keys
    .map((k) => {
      const c = BLOCK_COMMENTS[k] ? `  // ${BLOCK_COMMENTS[k]}\n` : "";
      return `${c}  ${renderKey(k)}: ${renderValue(partial[k], 1)},`;
    })
    .join("\n");
  const lines = [
    "// Reviewgate config — generated by `reviewgate init` (or its `setup` alias).",
    "// Data-only object, deep-merged over defaults + validated.",
    "// Imports, calls, spreads and environment expressions are rejected.",
    "export default {",
    ...(body ? [body] : []),
    "};",
    "",
  ];
  return lines.join("\n");
}
