const copyText=async(button,text)=>{try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent="Copied ✓";button.classList.add("copied");setTimeout(()=>{button.textContent=old;button.classList.remove("copied")},1600)}catch{button.textContent="Copy failed"}};
document.querySelectorAll("[data-copy]").forEach(el=>el.querySelector("button")?.addEventListener("click",()=>copyText(el.querySelector("button"),el.dataset.copy)));
document.querySelectorAll("[data-copy-target]").forEach(button=>button.addEventListener("click",()=>copyText(button,document.querySelector(button.dataset.copyTarget).innerText)));
const menu=document.querySelector(".menu"),nav=document.querySelector(".nav");menu?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))});
nav?.querySelectorAll("nav a").forEach(link=>link.addEventListener("click",()=>{nav.classList.remove("open");menu?.setAttribute("aria-expanded","false")}));
const setupContent={
  1:{title:"TERMINAL / 01 INSTALL",note:"The npm package installs only the prebuilt binary for your operating system and CPU architecture.",html:`<span class="comment"># Install your platform's prebuilt binary</span>\n<span class="prompt">$</span> npm i -g reviewgate\n\n<span class="ok">✓ reviewgate installed globally</span>`},
  2:{title:"TERMINAL / 02 INITIALIZE",note:"One command owns the complete first run: policy, hosts, native hooks, initial last-known-good fingerprint and health check.",html:`<span class="comment"># Enter the repository and start the guided flow</span>\n<span class="prompt">$</span> cd your-repo\n<span class="prompt">$</span> reviewgate init\n\n<span class="ok">? Protect: Claude Code + Codex (recommended)</span>`},
  3:{title:"TERMINAL / 03 CONFIGURE",note:"Custom mode covers reviewers, models, fallbacks, critic, memory, sandbox, SOFT-PASS policy, notifications and pre-push behavior.",html:`<span class="ok">? Setup mode: Custom</span>\n<span class="ok">? Reviewers: Codex, Gemini, Claude…</span>\n<span class="ok">? Reviewer subprocess sandbox: Strict</span>\n<span class="ok">✓ hooks installed · LKG recorded</span>`},
  4:{title:"TERMINAL / 04 ACTIVATE & VERIFY",note:"Installation is automatic; Codex activation is deliberately user-controlled. Trust the exact hash once, and repeat only when the generated definitions change.",html:`<span class="comment"># User action inside Codex — Reviewgate cannot self-approve</span>\n<span class="prompt">/</span>hooks\n<span class="ok">Review: SessionStart · PostToolUse · Stop</span>\n<span class="ok">Trust the exact current project-hook hash</span>\n\n<span class="comment"># Doctor verifies installation, not Codex's private trust store</span>\n<span class="prompt">$</span> reviewgate doctor`}
};
const setupCode=document.querySelector("#setup-code code"),setupTitle=document.querySelector("#setup-title"),setupNote=document.querySelector("#setup-note");
document.querySelectorAll(".step").forEach(step=>step.addEventListener("click",()=>{document.querySelectorAll(".step").forEach(s=>{s.classList.remove("active");s.setAttribute("aria-selected","false")});step.classList.add("active");step.setAttribute("aria-selected","true");const content=setupContent[step.dataset.step];if(setupCode&&setupTitle&&setupNote){setupCode.style.opacity="0";setTimeout(()=>{setupTitle.textContent=content.title;setupCode.innerHTML=content.html;setupNote.textContent=content.note;setupCode.style.opacity="1"},120)}}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll(".section h2,.flow article,.benefit-grid article,.metrics article").forEach(el=>{el.classList.add("observe");observer.observe(el)});
